version: '3.3'

services:
  db:
    image: redis:alpine
    volumes:
      - data:/data
    restart: always
    command: 'redis-server --appendonly yes'
  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      REDIS_HOST: 'db'
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    restart: always
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/example.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/localhost.crt:/etc/nginx/localhost.crt:ro
      - ./nginx/localhost.key:/etc/nginx/localhost.key:ro
    restart: always
volumes:
  data: